platform :ios, '11.4'

target 'BabyLikesWhatDlib' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 # Pods for BabyLikesWhatDlib
   pod 'OpenCV'

end
